### PR TITLE
closes #155 make compatible with keycloak >= 21.0.0

### LINKED ISSUE #155: Seems incompatible with Keycloak 21
## Description
After having migrated to Keycloak 21 (Quarkus) I get "Internal Server Error" whenever I try to login. The logs show messages like these:

`ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-7) HTTP Request to /auth/realms/jake/metrics failed, error id: fdebc248-5921-4c51-8db2-2bcbcff3607e-57: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: Failed to register Collector of type Counter: keycloak_login_attempts_total is already in use by another Collector of type Counter`

Keycloak 21 changed metrics implementation from SmallRye to Micrometer, maybe this clashes with this project somehow?

## Steps to reproduce
1. Install and enable keycloak-metrics-spi v2.5.3 on Keycloak 20
2. Migrate to Keycloak 21
3. Attempt to login to the admin console

### PR DESCRIPTION
**Pull request by ghenadiibatalski**
see naming conventions https://prometheus.io/docs/instrumenting/writing_exporters/#naming

The SPI seems to be incompatible with Keycloak >=21.0.0
This PR is switched to Java 17 and Keycloak 21.0 + Prometheus 0.16.0 compatibility

In this form it works on Keycloak 21.0.1 Quarkus on Java 17

## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: 
https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 

## What
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)

## Why
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)

## How
Add an short answer for: How it was done? (E.g By removing this feature from ... OR By removing just the button but not its implementation ... ) 

## Verification Steps
Add the steps required to check this change. Following an example.
 
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users.

### CODE REVIEW

File: src/test/java/org/jboss/aerogear/keycloak/metrics/PrometheusExporterTest.java [hunk 1]
```diff
@@ -349,7 +349,7 @@ private void assertMetric(String metricName, double metricValue, String realm, T
 
             final StringBuilder builder = new StringBuilder();
 
-            builder.append(metricName).append("{");
+            builder.append(metricName+"_total").append("{");
```
Comment (williancolognesitrimble) [inline src/test/java/org/jboss/aerogear/keycloak/metrics/PrometheusExporterTest.java:352]: as it's a stringbuilder, you could use append here too.
`builder.append(metricName).append("_total").append("{");`

it's slight more performatic

Comment (ghenadiibatalski) [reply src/test/java/org/jboss/aerogear/keycloak/metrics/PrometheusExporterTest.java:352]: Shure, it's up to maintainer. this is only a proposal which works, if you are maintainer, i could change it.

Comment (pb82) [reply src/test/java/org/jboss/aerogear/keycloak/metrics/PrometheusExporterTest.java]: thanks @ghenadiibatalski this is fine inside the unit test

**Comment by pb82** [comment]
@ghenadiibatalski is this the only change required to make it compatible with Keycloak 21?

**Comment by ghenadiibatalski** [comment]
@pb82 it works for me, but you should check the metrics names, they are suffixed now with _total, _sum, etc. I think, it is a feature of prometheus.

File: build.gradle [hunk 2]
```diff
@@ -13,11 +13,11 @@ configurations {
 }
 
 group 'org.jboss.aerogear'
-version '2.5.4-SNAPSHOT'
+version '3.0.0-SNAPSHOT'
 
 apply plugin: 'java'
 
-sourceCompatibility = 1.8
+sourceCompatibility = 17
```
Comment (pb82) [inline build.gradle:20]: This makes it incompatible with Keycloak <21

**Comment by pb82** [comment]
@ghenadiibatalski I've tested this with KC 19, 20 and 21. The only problem is the source compatibility bump, this makes it incompatible with older version. Is this needed?
Other than that i'd like to get this merged and released :+1:

File: build.gradle (hunk 2 above)
Comment (thomasdarimont) [reply build.gradle:20]: I think the KC images before KC 21 use Java 11. Using sourceLevel 11 should fix that.

Comment (pb82) [reply build.gradle:20]: thanks, that works for KC 21 and older versions too!

**Comment by pb82** [comment]
@ghenadiibatalski thanks, I'll merge this and follow up with another PR to set the source compatibility to Java 11.
